openapi: 3.0.3
info:
  title: LANCast API
  description: REST API for LANCast LAN video streaming platform
  version: 1.0.0

servers:
  - url: http://{host}:{port}
    description: Local LAN server
    variables:
      host:
        default: localhost
      port:
        default: '8080'

paths:
  /:
    get:
      summary: Viewer page
      description: Serves the main HTML page for watching the stream
      operationId: getViewerPage
      responses:
        '200':
          description: HTML page
          content:
            text/html:
              schema:
                type: string

  /api/status:
    get:
      summary: Get stream status
      description: Returns current stream status and metadata. Use WebSocket for real-time updates.
      operationId: getStatus
      responses:
        '200':
          description: Current stream status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamStatus'
              examples:
                offline:
                  summary: Stream offline
                  value:
                    live: false
                    viewerCount: 0
                live:
                  summary: Stream live
                  value:
                    live: true
                    viewerCount: 5
                    streamInfo:
                      resolution: "1920x1080"
                      bitrate: 5000
                      startTime: "2025-12-11T15:30:00Z"

  /media/live/master.m3u8:
    get:
      summary: HLS master playlist
      description: Master playlist for adaptive bitrate streaming
      operationId: getMasterPlaylist
      responses:
        '200':
          description: HLS master playlist
          content:
            application/vnd.apple.mpegurl:
              schema:
                type: string
              example: |
                #EXTM3U
                #EXT-X-VERSION:3
                #EXT-X-STREAM-INF:BANDWIDTH=5000000,RESOLUTION=1920x1080
                1080p/stream.m3u8
                #EXT-X-STREAM-INF:BANDWIDTH=2500000,RESOLUTION=1280x720
                720p/stream.m3u8
                #EXT-X-STREAM-INF:BANDWIDTH=1000000,RESOLUTION=854x480
                480p/stream.m3u8
        '404':
          description: No active stream
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /media/live/{quality}/stream.m3u8:
    get:
      summary: HLS quality playlist
      description: Playlist for specific quality level
      operationId: getQualityPlaylist
      parameters:
        - name: quality
          in: path
          required: true
          schema:
            type: string
            enum: ['1080p', '720p', '480p']
      responses:
        '200':
          description: HLS playlist
          content:
            application/vnd.apple.mpegurl:
              schema:
                type: string
        '404':
          description: Quality not available

  /media/live/{quality}/{segment}:
    get:
      summary: HLS segment
      description: Video segment file
      operationId: getSegment
      parameters:
        - name: quality
          in: path
          required: true
          schema:
            type: string
            enum: ['1080p', '720p', '480p']
        - name: segment
          in: path
          required: true
          schema:
            type: string
            pattern: '^stream\d+\.ts$'
      responses:
        '200':
          description: MPEG-TS segment
          content:
            video/mp2t:
              schema:
                type: string
                format: binary
        '404':
          description: Segment not found

components:
  schemas:
    StreamStatus:
      type: object
      required:
        - live
        - viewerCount
      properties:
        live:
          type: boolean
          description: Whether a stream is currently active
        viewerCount:
          type: integer
          minimum: 0
          maximum: 10
          description: Number of connected viewers
        streamInfo:
          $ref: '#/components/schemas/StreamInfo'

    StreamInfo:
      type: object
      description: Metadata about the active stream (only present when live)
      required:
        - resolution
        - bitrate
        - startTime
      properties:
        resolution:
          type: string
          pattern: '^\d+x\d+$'
          example: "1920x1080"
          description: Stream resolution
        bitrate:
          type: integer
          minimum: 0
          example: 5000
          description: Stream bitrate in kbps
        startTime:
          type: string
          format: date-time
          description: ISO 8601 timestamp of stream start

    Error:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
